//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaDiem
    {
        public string MaDD { get; set; }
        public string TebDD { get; set; }
        public Nullable<int> GiaTien { get; set; }
    }
}
