//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuVe
    {
        public int stt { get; set; }
        public string MaPhieu { get; set; }
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string MaNVBV { get; set; }
        public string TenNVBV { get; set; }
        public Nullable<int> SoTien { get; set; }
        public string ChoNgoi { get; set; }
        public string MaChuyenxe { get; set; }
        public Nullable<System.DateTime> NgayKhoiHanh { get; set; }
        public string TenDD { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
